### ISSUE TITLE
Move ed messages to 'ed_msgs'

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/ed#42]
Just like every other ros package (e.g. moveit_msgs) we could move the messages and services to a separate package. This will separate interface from implementation.

As a side effect the python code can more easily be unit-tested because it will not depend on the full ed anymore.

New package: https://github.com/tue-robotics/ed_msgs

## PRs

- [x] tue-robotics/cb_base_navigation#12
- [x] tue-robotics/ed#53
- [x] tue-robotics/ed_object_models#14
- [x] tue-robotics/head_ref_ed_client#3
- [x] tue-robotics/nl_robot_console#18
- [x] tue-robotics/tue-env#179
- [x] tue-robotics/tue_mobile_ui#18
- [x] tue-robotics/tue_robocup#428
- [x] tue-robotics/ed_sensor_integration#13
- [ ] did we forgot any repo?

**Comment by LoyVanBeek** [comment]
+1

**Comment by MatthijsBurgh** [comment]
These are all the repos I could find.
Action server does depend on ED, but not sure why, because it doesn't import from ed.
